

services:
  devopsdb:
    image: dbimg
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: appimg
    ports:
      - "1111:8080"
    deploy:
      replicas: 2
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
