---
services:
  devopsdb:
    image: dbimg
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - network1
      

  application:
    image: appimg
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
    depends_on:
      - devopsdb
    networks:
      - network2
     

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge
